#!/bin/bash
echo starting to install stylometry project
chmod 775 part1RPM.sh
./part1RPM.sh
chmod 775 part2RPM.sh
./part2RPM.sh
chmod 775 part3RPM.sh
./part3RPM.sh
chmod 775 part4RPM.sh
./part4RPM.sh
sudo cp CodeStylometry-missing-joern-tools-files/steps/featureExtraction.groovy /usr/local/lib/python2.7/site-packages/joerntools-0.1-py2.7.egg/joerntools/steps
sudo cp CodeStylometry-missing-joern-tools-files/steps/featureExtraction.groovy /usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/steps
echo done installing
