#!/bin/bash
echo starting to install stylometry project
chmod 775 part1Debian.sh
./part1Debian.sh
chmod 775 part2Debian.sh
./part2Debian.sh
chmod 775 part3Debian.sh
./part3Debian.sh
chmod 775 part4.sh
./part4.sh
echo done installing
