#!/bin/bash
echo starting to install stylometry project
chmod 775 part1Debian.sh
./part1Debian.sh
chmod 775 part2Debian.sh
./part2Debian.sh
chmod 775 part3Debian.sh
./part3Debian.sh
chmod 775 part4Debian.sh
./part4Debian.sh
sudo cp CodeStylometry-missing-joern-tools-files/steps/featureExtraction.groovy /usr/local/lib/python2.7/site-packages/joerntools-0.1-py2.7.egg/joerntools/steps
sudo cp CodeStylometry-missing-joern-tools-files/steps/featureExtraction.groovy /usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/steps
echo done installing
