#!/bin/bash
echo starting to install stylometry project
chmod 775 part1RPM.sh
./part1RPM.sh
chmod 775 part2RPM.sh
./part2RPM.sh
chmod 775 part3RPM.sh
./part3RPM.sh
chmod 775 part4RPM.sh
./part4RPM.sh
echo done installing
